app/home/__init__.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/home/routes.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from app.home import blueprint
from flask import request, render_template, redirect, url_for, jsonify, session
from flask_login import login_required, current_user
import requests
from app import login_manager
from jinja2 import TemplateNotFound
from app.base.models import FirestoreCollectionCrud, Route
import firebase_admin
from app.base.models import all_tags
from app.base.constants import grade_options
from app.base.forms import AddRouteForm, EditProfileForm
from app.base.jinja_classes import StatsCard
import json
from datetime import datetime, time
import json


@blueprint.route('/index')
@login_required
def index():
    
    if not current_user.is_authenticated:
       return redirect(url_for('base_blueprint.login'))

    routes = FirestoreCollectionCrud('centres/' + session['centre_name'] + '/routes', Route).get_all()
    routes = [route for route in routes]

    number_of_routes = len(routes)
    number_of_sessions = "Not yet implemented"
    number_of_people = "Not yet implemented"

    stat_cards = [StatsCard(number_of_routes, big_icon="timeline", title="Number of Current Routes",
                        card_type="primary", footer_type="primary", footer_icon="timeline", footer_href="",
                        footer_text="nothing"),
                  StatsCard(number_of_sessions, big_icon="timeline", title="Number of sessions last week",
                            card_type="primary", footer_type="primary", footer_icon="timeline", footer_href="",
                            footer_text="nothing"),
                  StatsCard(number_of_people, big_icon="timeline", title="Number of people who attended last week",
                        card_type="primary", footer_type="primary", footer_icon="timeline", footer_href="",
                        footer_text="nothing")]

    return render_template('index.html', stat_cards=stat_cards)

@blueprint.route('/<template>')
@login_required
def route_template(template):

    if not current_user.is_authenticated:
        return redirect(url_for('base_blueprint.login'))

    try:

        return render_template(template + '.html')

    except TemplateNotFound:
        return render_template('page-404.html'), 404
    
    except:
        return render_template('page-500.html'), 500


@blueprint.route('/<user_type>/<template>', methods=["GET", "POST"])
@login_required
def route_centre_template(user_type, template):
    if not current_user.is_authenticated:
        return redirect(url_for('base_blueprint.login'))


    if "upload_profile" in request.form:
        current_user.upload_profile(request.files["image"])
    print(current_user.floorplan)
    if current_user.data['account_type'] == 'centre':

        if not 'centre_name' in session:
            session['centre_name'] =current_user.data['name']

        routes = FirestoreCollectionCrud('centres/' + session['centre_name'] + '/routes', Route).get_all()
        routes = [route for route in routes]
        routes_json = json.dumps([route.to_serialisable() for route in routes])
        return render_template(template + '.html', routes=routes, routes_json=routes_json)

        try:
            a=1
        except TemplateNotFound:
            return render_template('page-404.html'), 404
        except:
            return render_template('page-500.html'), 500

    else:
        return render_template('page-403.html'), 403

@blueprint.route('/centre/centre-profile', methods=["GET", "POST"])
@login_required
def centre_profile():
    notifications = []
    if not current_user.is_authenticated:
        return redirect(url_for('base_blueprint.login'))
    else:
        form = EditProfileForm()
        if request.method == "GET":
            form.about_the_centre.data = current_user.data.get('about', "")
            form.centre_name.data = current_user.data.get('name', "")
            form.address.data = current_user.data.get('address', "")
            form.country.data = current_user.data.get('country', "")
            form.city.data = current_user.data.get('city', "")
            form.postcode.data = current_user.data.get('postcode', "")
            form.grade_system.data = current_user.data.get('default_grade_system', "")

            return render_template('centre-profile.html', form=form, notifications=notifications)
        else:
            print(f"grade system data: {form.grade_system.data}")
            if form.validate_on_submit():

                data = {"about": form.about_the_centre.data, "name": form.centre_name.data,
                        "default_grade_system": form.grade_system.data, "address": form.address.data,
                        "country": form.country.data, "city": form.city.data, "postcode": form.postcode.data}
                for pic in ["profile_picture", "floor_plan"]:
                    file = request.files[pic]
                    if file.filename != '':
                        print(file.filename)
                        notifications.append(current_user.upload_image(file, pic))

                current_user.update_user(data)
            notifications += [("danger", "Error!", error) for error in form.errors]
            return render_template('centre-profile.html', form=form, notifications=notifications)


@blueprint.route('/_get_grades_list/')
def _get_grades_list():
    grade_system = request.args.get('grade_system', type=str)
    grades_list = [(str(i), grade) for i, grade in enumerate(grade_options[grade_system])]
    return jsonify(grades_list)


@blueprint.route('/get_floorplan/', methods=["GET"])
def _get_floor_plan():
    floorplan = current_user.floorplan
    return floorplan


@blueprint.route('/delete_route_<uid>', methods=["GET", "POST"])
@login_required
def delete_route(uid):
    return jsonify(FirestoreCollectionCrud('centres/' + session['centre_name'] + '/routes', Route).delete_item(uid))


@blueprint.route('/edit_route_<uid>', methods=["GET", "POST"])
@login_required
def edit_route(uid):

    routes_crud = FirestoreCollectionCrud('centres/' + session['centre_name'] + '/routes', Route)
    route = routes_crud.read_item(uid)

    route_form_data = {'uid': route.uid, 'name': route.name, 'grade': str(route.difficulty), 'date_added': route.date_added,
                       'tags_list': route.tags, 'x': route.floorplan_x, 'y': route.floorplan_y, 'grade_system': '0'}

    edit_route_form = AddRouteForm(request.form, data=route_form_data, obj=route)
    if edit_route_form.validate_on_submit():
        new_route = create_route_from_form(request.form).to_dict()
        routes_crud.update_item(uid, new_route)

        return redirect(url_for('home_blueprint.route_centre_template', user_type=current_user.data['account_type'],
                                template="manage-routes"))
    else:
        print(edit_route_form.errors)

    return render_template('create_route.html', form=edit_route_form, existing_route=route_form_data)


@blueprint.route("/centre/create_route", methods=["GET", "POST"])
@login_required
def create_route():
    create_route_form = AddRouteForm(request.form)
    print(create_route_form.grade.data)
    if create_route_form.validate_on_submit():
        route = create_route_from_form(request.form)
        FirestoreCollectionCrud('centres/' + session['centre_name'] + '/routes', Route).create_item(route.to_dict(), item_id="auto")

        return redirect(url_for('home_blueprint.route_centre_template', user_type=current_user.data['account_type'], template="manage-routes"))

    else:
        print(create_route_form.errors)

    return render_template('create_route.html', form=create_route_form)


def create_route_from_form2(form):
    tag_ids = form.tags_list.data
    difficulty_str = form.grade.data
    date_added = form.date_added.data
    name = form.name.data
    floorplan_x, floorplan_y = form.coordinates.data
    route = Route(name=name, difficulty=int(difficulty_str), tags=tag_ids, date_added=date_added,
                  floorplan_x=floorplan_x, floorplan_y=floorplan_y)

    return route


def create_route_from_form(form):

    tag_ids = form.getlist('tags_list')
    grade_str = request.form.getlist('grade')[0]
    date_added = datetime.combine(datetime.strptime(form.getlist('date_added')[0], '%Y-%m-%d'), time())
    name = form.getlist('name')[0]
    floorplan_x, floorplan_y = map(int, form.getlist('coordinates')[0].replace("(", "").replace(")", "").split(','))
    route = Route(name=name, difficulty=int(grade_str) - 1, tags=tag_ids, date_added=date_added,
                  floorplan_x=floorplan_x, floorplan_y=floorplan_y)

    return route

app/home/templates/climb_row.html
<tr id="route_table_row_{{route.uid}}">
  <td>
    {{route.uid}}
  </td>
  <td>
    {{route.name}}
  </td>
  <td>
    {{route.grade(current_user.data['default_grade_system'])}}
  </td>
  <td>
    {{route.tags_str}}
  </td>
  <td class="text-primary">
    {{route.format_date()}}
  </td>
  <td class="td" id="edit_route_{{route.uid}}">
    <a type="button" class="btn btn-primary">
      <i class="material-icons" >edit</i>
    </a>
  </td>
  <td class="td" id="delete_route_{{route.uid}}">
    <a type="button" class="btn btn-danger" >
      <i class="material-icons">close</i>
    </a>
  </td>
</tr>

app/home/templates/create_route.html
{% extends "base-site.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
{% endblock stylesheets %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">
            Route Manager
          </h4>
        </div>
        <div class="card-body">

          <h6 class="card-category">
                <span class="text-danger">{{ msg | safe }}</span>
                    <span>
                      {% if existing_route %}
                        Edit route: {{existing_route['uid']}}
                      {% else %}
                        Create New Route
                      {% endif %}
                    </span>
          </h6>
          
          <br />

          <form role="form" method="post" action="">
            {{ form.hidden_tag() }}
          <div class="row">
            <div class="col">
              <label class="bmd-label-floating">Select a Location!</label>
              <div id="floorplan"></div>
            </div>
          </div>
            <div class="row">
              <div class="col">
                <div class="form-group" id="form_group_coordinates">
                  <label class="bmd-label-floating" >Route coordinates</label>
                  {{ form.coordinates(**{"class_":"form-control","type":"text"}) }}
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="form-group">
                  <label class="bmd-label-floating">Route Name</label>
                  {{ form.name(class_="form-control") }}
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  <label>Date Added</label>
                    {{ form.date_added(**{"class_":"form-control"}) }}
                </div>
              </div>
            </div>

            <br />

            <div class="row">
              <div class="col">
                <div class="row">
                  <div class="form-group">
                      <label>Grading System</label>
                      {{ form.grade_system(**{"class_":"custom-select"}) }}
                  </div>
                </div>
                <div class="row">
                  <div class="form-group">
                    <label>Grade</label>
                        {{ form.grade(**{"class_":"custom-select"})}}
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  <label>Tags</label>
                    {{ form.tags_list(**{"class_":"custom-select", "aria-describedby": "tagsHelpBlock"}) }}
                    <small id="tagsHelpBlock" class="form-text text-muted">
                      You can choose as many tags as you like
                    </small>
                </div>
              </div>
            </div>

            <br/>
            <div class="form-group">
              {{ form.submit(class="btn btn-primary pull-left", type="submit") }}
            </div>
            <div class="clearfix"></div>

          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

    <script>
      $(function() {
         {% if current_user.floorplan is not none %}
            var url = "{{url_for('home_blueprint._get_floor_plan') }}";
            var max_w = 1000;
            var max_h = 500;
            var main_chart_svg = d3.select("#floorplan").append("svg").attr("height",max_h).attr("width",max_w).attr("id","main_chart_svg");

            create_circle = (x,y) => {
                var floorplan_svg = d3.select("#floorplan_svg");
                var location_circle = d3.select("#route_location");
                if (location_circle.empty()){
                    main_chart_svg.append("circle").attr("width",200)
                    .attr("id", "route_location")
                    .attr("r",10)
                    .attr("fill","red")
                    .attr("stroke","blue")
                    .attr("stroke-width",1);
                }
                var location_circle = d3.select("#route_location");
                location_circle.attr("cx",x).attr("cy",y);

                $('#coordinates').val(`(${x}, ${y})`).change();
                $('#coordinates').attr('value',`(${x}, ${y})`).change();
                $('#coordinates').prop('value',`(${x}, ${y})`).change();

                $('#form_group_coordinates').attr("class","form-group bmd-form-group is-filled");
            }

            d3.xml(url).then(data => {
              main_chart_svg.node().append(data.documentElement);
              var floorplan_svg = d3.select("svg").select("svg");
              var scale_ratio = Math.min(max_w/floorplan_svg.attr("width"), max_h/floorplan_svg.attr("height"));
              var svg_height = floorplan_svg.attr("height") * scale_ratio;
              var svg_width = floorplan_svg.attr("width") * scale_ratio;
              floorplan_svg.attr("height",svg_height).attr("width", svg_width).attr("id","floorplan_svg").attr("x",0).attr("y",0);
              {% if existing_route %}
                create_circle({{existing_route['x']}},{{existing_route['y']}});
              {% endif %}

              d3.select("#floorplan_svg").on("click", function() {

                  var data = d3.mouse(this);
                  var x = Math.floor(data[0]*scale_ratio/10)*10;
                  var y = Math.floor(data[1]*scale_ratio/10)*10;
                  create_circle(x,y);

              });

            });


          {% endif %}

          // jQuery selection for the 2 select boxes
          var dropdown = {
              grade_system: $('#grade_system_select'),
              grades: $('#grade_select')
          };

          {% if existing_route %}
          //$('#tags_list').val({{existing_route['tags_list']}});
          var grade = {{existing_route['grade']}};
          // call to update on load
           updateGradeSystem(grade);
          {% else %}
            updateGradeSystem("0");
          {% endif %}




          // function to call XHR and update county dropdown
          function updateGradeSystem(currentGrade) {
              var send = {
                  grade_system: dropdown.grade_system.val()
              };
              dropdown.grades.empty();
              $.getJSON("{{ url_for('home_blueprint._get_grades_list') }}", send, function(data) {
                  data.forEach(function(item) {
                      console.log(`${item[0]},${currentGrade}`);
                      if (currentGrade == item[0]){
                          dropdown.grades.append(
                          $('<option>', {
                              value: item[0],
                              text: item[1],
                              selected: "selected"
                          })
                          );
                      } else {
                          dropdown.grades.append(
                          $('<option>', {
                              value: item[0],
                              text: item[1]
                          })
                      );
                     }
                  });
              });
          }

          // event listener to state dropdown change
          dropdown.grade_system.on('change', function() {

              const current_grade = $('#grade_select').val();
              updateGradeSystem(current_grade);

          });


      });
    </script>
{% endblock javascripts %}

app/home/templates/index.html
{% extends "base-site.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">

      {% set count = 1 -%}
      {% for stat_card in stat_cards %}
        {% if count/3 == 0 %}
          <div class="row">
        {% endif %}
          <div class="col-md-4">
          {% include "stats_card.html" %}
          </div>
        {% if count/3 == 0 %}
          </div>
        {% endif %}
        {% set count = count + group|length %}
      {% endfor %}
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="card card-chart">
          <div class="card-header card-header-success">
            <div class="ct-chart" id="dailySalesChart"></div>
          </div>
          <div class="card-body">
            <h4 class="card-title">Daily Sales</h4>
            <p class="card-category">
              <span class="text-success"><i class="fa fa-long-arrow-up"></i> 55% </span> increase in today sales.</p>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">access_time</i> updated 4 minutes ago
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card card-chart">
          <div class="card-header card-header-warning">
            <div class="ct-chart" id="websiteViewsChart"></div>
          </div>
          <div class="card-body">
            <h4 class="card-title">Email Subscriptions</h4>
            <p class="card-category">Last Campaign Performance</p>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">access_time</i> campaign sent 2 days ago
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card card-chart">
          <div class="card-header card-header-danger">
            <div class="ct-chart" id="completedTasksChart"></div>
          </div>
          <div class="card-body">
            <h4 class="card-title">Completed Tasks</h4>
            <p class="card-category">Last Campaign Performance</p>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">access_time</i> campaign sent 2 days ago
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      md.initDashboardPageCharts();

    });
  </script>

{% endblock javascripts %}

app/home/templates/manage-circuits.html
{% extends "base-site.html" %}

{% block title %} Manage Routes {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <button type="submit" name="login" class="btn btn-primary pull-left">Login</button>
        {% for circuit in circuits %}
        <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title "> {{circuit.name}}</h4>
                  <p class="card-category"> {{circuit.description}} </p>
                  <p class="card-category"> {{circuit.grade_range}} </p>
                  <p class="card-category"> {{circuit.style}} </p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead class=" text-primary">
                        <th>
                          Route ID
                        </th>
                        <th>
                          Name
                        </th>
                        <th>
                          Difficulty
                        </th>
                        <th>
                          Tags
                        </th>
                        <th>
                          Date Added
                        </th>
                      </thead>
                      {% for route in circuit.routes %}
                      <tbody>
                        <tr>
                          <td>
                            {{route.id}}
                          </td>
                          <td>
                            {{route.name}}
                          </td>
                          <td>
                            {{route.difficulty}}
                          </td>
                          <td>
                            {{route.tags_str}}
                          </td>
                          <td class="text-primary">
                            {{route.date_added}}
                          </td>
                        </tr>
                      </tbody>
                      {% endfor %}
                    </table>
                  </div>
                </div>
              </div>
            </div>
        </div>
        {% endfor %}
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/home/templates/manage-routes.html
{% extends "base-site.html" %}

{% block title %} Manage Routes {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<style>
    div.tooltip-donut {
     position: absolute;
     text-align: center;
     padding: .5rem;
     background: #FFFFFF;
     color: #313639;
     border: 1px solid #313639;
     border-radius: 8px;
     pointer-events: none;
     font-size: 1.3rem;
}

</style>
{% endblock stylesheets %}

{% block content %}
    {% if current_user.floorplan is not none %}
    <div class="row">
        <div class="col-md-12">
            <div id="floorplan"></div>
        </div>
    </div>
    {% else %}
        <a > floor plan has not yet been uploaded </a>
        <div class="col-md-3">
            <a class="btn btn-default btn-block" href = {{url_for('home_blueprint.centre_profile') }}>
                Go to Centre Profile
            </a>
        </div>
    {% endif %}
        <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-primary">
                  <div class="row">
                    <div class="col-md-6">
                        <h4 class="card-title ">Routes</h4>
                        <p class="card-category"> All Routes</p>
                     </div>
                    <div class="col-md-auto">
                        <a class="btn btn-default btn-block" href = {{url_for('home_blueprint.create_route') }}>
                          Create Route
                        </a>
                     </div>
                  </div>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table  id="routesTable"  style="width:100%" class="display" >
              <thead class=" text-primary">
                <th>
                  Route ID
                </th>
                <th>
                  Name
                </th>
                <th>
                  Grade
                </th>
                <th>
                  Tags
                </th>
                <th>
                  Date Added
                </th>
                <th>
                  Edit Climb
                </th>
                <th>
                  Delete Climb
                </th>
              </thead>
              <tbody>
              {% for route in routes %}
                {% include 'climb_row.html' %}
              {% endfor %}
              </tbody>
            </table>
                  </div>
                </div>
              </div>
            </div>

        </div>

{% endblock content %}

{% block javascripts %}
<!-- Specific Page JS goes HERE  -->
    <script>
        $(function(){

            var table = $('#routesTable').DataTable();

            class Circle {
                constructor(floorplan_x, floorplan_y) {
                this.floorplan_x = height;
                this.floorplan_y = width;
                }
            }

            function filterTable() {
                //number of filtered rows

            }
            table.on('search.dt', function(){
                table.rows( { search : 'applied'} ).data();


                var circles = main_chart_svg.selectAll("circle").data({{routes_json | safe}})
                .enter().append("circle");
            });


            callout = (g, value) => {
            if (!value) return g.style("display", "none");

            g.style("display", null)
            .style("pointer-events", "none")
            .style("font", "10px sans-serif");

            const path = g.selectAll("path")
                .data([null])
                .join("path")
                .attr("fill", "white")
                .attr("stroke", "black");

            const text = g.selectAll("text")
                .data([null])
                .join("text")
                .call(text => text
                    .selectAll("tspan")
                    .data((value + "").split(/\n/))
                    .join("tspan")
                    .attr("x", 0)
                .attr("y", (d, i) => `${i * 1.1}em`)
                .style("font-weight", (_, i) => i ? null : "bold")
                .text(d => d));
            const {x, y, width: w, height: h} = text.node().getBBox();

            text.attr("transform", `translate(${-w / 2},${15 - y})`);
            path.attr("d", `M${-w / 2 - 10},5H-5l5,-5l5,5H${w / 2 + 10}v${h + 20}h-${w + 20}z`);

            }

             {% if current_user.floorplan is not none %}
                var url = "{{url_for('home_blueprint._get_floor_plan') }}";
                var max_w = 1000;
                var max_h = 500;
                var main_chart_svg = d3.select("#floorplan").append("svg").attr("height",max_h).attr("width",max_w).attr("id","main_chart_svg");
                var div = d3.select("#floorplan").append("div")
                .attr("class", "tooltip-donut")
                .style("opacity", 0);

                d3.xml(url).then(data => {
                    main_chart_svg.node().append(data.documentElement);
                    var floorplan_svg = d3.select("svg").select("svg");
                    var scale_ratio = Math.min(max_w/floorplan_svg.attr("width"), max_h/floorplan_svg.attr("height"));
                    var svg_height = floorplan_svg.attr("height") * scale_ratio;
                    var svg_width = floorplan_svg.attr("width") * scale_ratio;
                    floorplan_svg.attr("height",svg_height).attr("width", svg_width).attr("id","floorplan_svg").attr("x",0).attr("y",0);

                    var circles = main_chart_svg.selectAll("circle").data({{routes_json | safe}})
                    .enter().append("circle");

                    var circleAttributes = circles
                    .attr("cx", function (d) { return d.floorplan_x;})
                    .attr("cy", function (d) { return d.floorplan_y;})
                    .attr('opacity', '1')
                    .attr("r", 10 ).attr("fill","red")
                    .attr("stroke","blue")
                    .attr("stroke-width",1)
                    //Our new hover effects
                    .on('mouseover', function (d, i) {
                        d3.select(this).transition()
                        .duration('1')
                        .attr('opacity', '.2');

                        coordinate = d3.mouse(this);
                       //Makes the new div appear on hover:
                        tooltip
                        .attr("transform",`translate(${coordinate[0]},${coordinate[1]})`)
                        .call(callout,`${d.name}\n${d.difficulty}`);

                        })
                    .on('mouseout', function (d, i) {
                        d3.select(this).transition()
                        .duration('1')
                        .attr('opacity', '1');
                        tooltip.call(callout, null);

                        });

                     const tooltip = main_chart_svg.append("g");
                });



            {% endif %}

            {% for route in routes %}
              $( "#delete_route_{{route.uid}}" ).on( "click", function(event) {
                 $.post("{{url_for('home_blueprint.delete_route', uid= route.uid)}}").done(function(response){
                    if (response['success']== true){
                      $.notify({title: '<strong>Success!</strong>', message: 'Route was successfully deleted.'}, {type: 'success'});
                      $("#route_table_row_{{route.uid}}").remove();
                    }
                    else {
                      $.notify({title: '<strong>Error!</strong>',message: 'Route could not be deleted'}, {type: 'warning'});
                    }
                  }).fail(function() {
                      $.notify({ title: '<strong>Error!</strong>', message: 'Route could not be deleted'}, {type: 'warning'});
                  });
              });
              $( "#edit_route_{{route.uid}}" ).on( "click", function(event) {
                  window.location.replace("{{url_for('home_blueprint.edit_route', uid= route.uid)}}");
              });
            {% endfor %}

        });

    </script>
{% endblock javascripts %}

app/home/templates/page-403.html
{% extends "errors/403.html" %}

app/home/templates/page-404.html
{% extends "errors/404.html" %}

app/home/templates/page-500.html
{% extends "errors/500.html" %}

app/home/templates/page-blank.html
{% extends "base-site.html" %}

{% block title %} Page Blank {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Page Blank</h6>
                    <h4 class="card-title">
                        Add your content 
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}